apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set-first
spec:
  selector:
    matchLabels:
      ssd: "true"
  template:
    metadata:
      labels:
        ssd: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80

