apiVersion: v1
kind: Namespace
metadata:
  name: giropops
spec:
  finalizers:
    - kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: nginx
  name: meu-nginx
  namespace: giropops
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: giropops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    nodePort: 32222
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort
