apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    nodePort: 32333
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
