apiVersion: v1
kind: Namespace
metadata:
  name: giropops2
spec:
  finalizers:
    - kubernetes

---

apiVersion: v1
kind: LimitRange
metadata:
  name: resources-limited
spec:
  limits:
  - default:
      cpu: 1
      memory: 256Mi
    defaultRequest:
      cpu: 0.5
      memory: 128Mi
    type: Container
